Feature/historic page
l-huisman/The-Festival pull request #31
Opened 2024-02-29 03:24 UTC by FejsalA

2024-02-29 07:45 UTC, l-huisman requested changes

2024-02-29 07:45 UTC, l-huisman commented on app/controllers/historicController.php
Je variabel namen zijn niet erg descriptive, probeer er voor te zorgen dat je kan aflezen wat er in een variabel zit.

2024-02-29 07:45 UTC, l-huisman commented on app/repositories/historicRepository.php
> +        $stmt = $this->connection->prepare("SELECT * FROM historicEvent");
SELECT specific data points!

2024-02-29 07:45 UTC, l-huisman commented on app/repositories/historicRepository.php
> +        $stmt->bindParam('', $description);
???, wat nou als je de description wilt updated?

2024-02-29 07:45 UTC, l-huisman commented on app/router/dynamicRouter.php
> +
Je kan values doorgeven via de url als je hier niet uitkomt wil ik je wel helpen, hiervoor heb je geen static route nodig.

### Als dit test route was vergeet niet er uit te halen

2024-02-29 07:45 UTC, l-huisman commented on app/services/historicService.php
> +        $repository = new HistoricRepository();
Als je een class in meerdere functions gebruikt kan je hem beter instantieëren in de constructor, ander heb je misschien het probleem dat hij niet word aangemaakt!

2024-02-29 07:45 UTC, l-huisman commented on app/services/historicService.php
> +        $data = $this->repository->getHistoricEventById($id);
???Waar???

2024-02-29 07:45 UTC, l-huisman commented on app/views/elements/header.php
> +                <a class="nav-link" href="\historic">History</a>
Voor consistency gebruik s.v.p. '/' in plaats van '\'

2024-02-29 07:45 UTC, l-huisman commented on app/views/historic/historicOverview.php
> +        </style>
### PLEASE USE A STYLESHEET!!!

2024-02-29 07:45 UTC, l-huisman commented on app/views/historic/historicOverview.php
> +<? foreach($historic as $h){
Je kan html en php in elkaar verwerken zet op de plekken van de variabellen <?= event->getName() ?> <--- Dit kan je tussen normaal html gebruiken

2024-02-29 07:45 UTC, l-huisman commented on app/views/historic/historicOverview.php
> +                        <img src="https://www.awanderlustforlife.com/wp-content/uploads/2015/12/Haarlem_Title.jpg" alt="" />
Foto's s.v.p. downloaden en toevoegen in public map en ook uit de path database halen.

2024-02-29 07:45 UTC, l-huisman commented on app/views/home.php
>          .carousel-inner img {
Stylesheet s.v.p.

2024-02-29 08:44 UTC, ThijsMoerland approved these changes

2024-03-12 19:57 UTC, l-huisman commented on app/repositories/historicRepository.php
> +        $stmt->bindParam('', $description);
Schrijf hier iniedengeval een reactie op ofzo, waarom je dit zo hebt gedaan dan kunnen we kijken of het resolved kan worden.

2024-03-12 19:58 UTC, l-huisman commented on app/router/dynamicRouter.php
> +
Schrijf hier iniedengeval een reactie op ofzo, waarom je dit zo hebt gedaan dan kunnen we kijken of het resolved kan worden.

2024-03-12 20:00 UTC, l-huisman commented on app/services/historicService.php
> +        $repository = new HistoricRepository();
Vergeet hem niet nu hier aan te passen: 
Deze line kan weg $repository = new HistoricRepository(); 
Deze line updaten naar $historic = $this->repository->getAllHistoricEvents();

2024-03-12 20:00 UTC, l-huisman commented on app/services/tourService.php
> +
Waarom zijn er zo veel returns hier?

2024-03-12 20:01 UTC, l-huisman commented on app/views/historic/historicDetail.php
> +<h1 class="display-5 fw-bold"><?= $event->getName(); ?></h1>
Super!

2024-03-12 20:03 UTC, l-huisman commented on app/views/historic/historicOverview.php
> +<? foreach($historic as $h){
## Please fix! <?= $variable->getDataPoint() ?>, don't use echo!!!!!

2024-03-12 20:05 UTC, l-huisman requested changes
# Not all comments have been resolved please do so then this PR can finally be merged!!!!!!

2024-03-13 10:48 UTC, l-huisman approved these changes
Minor issues, approved!

2024-03-13 10:48 UTC, merged